### ISSUE TITLE
Add photos from email

### ISSUE THREAD

**Issue by HacKurx** [Offerel/roundcube_pictures#2]
Hi,

If I understand the gallery needs an absolute path. It would be nice to have the same functionality as [yahoo mail](https://www.ymail.info/wp-content/uploads/2017/10/Yahoo-7.jpg) i.e. a gallery that would display the images contained in all emails.

Hopefully that will happen, thank you.

**Comment by Offerel** [comment]
I didn't have  a Yahoo account. But maybe you could describe a little bit more in detail, what you mean with "display images contained in all emails".

If you mean that there is a button in the gallery which display's all images that are a e-mail attachment, than i don't know a good way to do this. This would mean, that the gallery plugin must have access to all e-mails, in all folders. I have serious personal privacy concerns with this. 

If you mean, to have button in the opened mail, where you could save a single attached picture to the gallery folder (or better a subfolder of the gallery), than this would be the better way.

**Comment by HacKurx** [comment]
> If you mean that there is a button in the gallery which display's all images that are a e-mail attachment, than i don't know a good way to do this. 

Yes. It's possible to use "[munpack](https://askubuntu.com/questions/344636/how-can-i-extract-images-from-a-raw-email)" command for the messages in MIME and copy the images into the user-specific gallery.

> This would mean, that the gallery plugin must have access to all e-mails, in all folders.

He will have the rights of the user who opens his mailbox. Other users will not be able to see other users' galleries so just theirs.

**Comment by Offerel** [comment]
"munpack" seems to be a third-party application not a standard application for a LAMP installation. The user must install the package additionally to be able to use it. I'm afraid no one will do that on his server. If I see this correctly, munpack works directly with *.eml files. This would mean that the server with the roundcube installation would have to download the entire mailbox for account xy. If we consider that a standard account is usually more than 2GB in size, all this has to be downloaded into the roundcube installation, then all e-mails have to be saved/converted in *.eml format in order to parse every single e-mail afterward to pictures in a third step. 

This is too time-consuming for a normal setup. This would only make sense on a server where Roundube can access the mailbox directly and all emails are accessible as *.eml files without conversion. But even in this case, the server must scan every mail for images. That's not a good idea.

For the reasons mentioned above, I do not want to include such a function in the plugin. But you are welcome to create a fork and create this function for yourself.

**Comment by HacKurx** [comment]
> But you are welcome to create a fork and create this function for yourself.

Okay, no problem. Bye.
